package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 관리자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Admin implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 관리자번호. */
	private Integer adminSeq;

	/** 아이디. */
	private String adminId;

	/** 비밀번호. */
	private String adminPassword;

	/** 이름. */
	private String adminName;

	/** 전화번호. */
	private String adminPhone;

	/** 등급. */
	private String adminRating;

	/**
	 * 생성자.
	 */
	public Admin() {
	}
	
	

	public Admin(Integer adminSeq, String adminId, String adminPassword, String adminName, String adminPhone,
			String adminRating) {
		super();
		this.adminSeq = adminSeq;
		this.adminId = adminId;
		this.adminPassword = adminPassword;
		this.adminName = adminName;
		this.adminPhone = adminPhone;
		this.adminRating = adminRating;
	}



	/**
	 * 관리자번호을 설정합니다..
	 * 
	 * @param adminSeq
	 *            관리자번호
	 */
	public void setAdminSeq(Integer adminSeq) {
		this.adminSeq = adminSeq;
	}

	/**
	 * 관리자번호을 가져옵니다..
	 * 
	 * @return 관리자번호
	 */
	public Integer getAdminSeq() {
		return this.adminSeq;
	}

	/**
	 * 아이디을 설정합니다..
	 * 
	 * @param adminId
	 *            아이디
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/**
	 * 아이디을 가져옵니다..
	 * 
	 * @return 아이디
	 */
	public String getAdminId() {
		return this.adminId;
	}

	/**
	 * 비밀번호을 설정합니다..
	 * 
	 * @param adminPassword
	 *            비밀번호
	 */
	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	/**
	 * 비밀번호을 가져옵니다..
	 * 
	 * @return 비밀번호
	 */
	public String getAdminPassword() {
		return this.adminPassword;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param adminName
	 *            이름
	 */
	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getAdminName() {
		return this.adminName;
	}

	/**
	 * 전화번호을 설정합니다..
	 * 
	 * @param adminPhone
	 *            전화번호
	 */
	public void setAdminPhone(String adminPhone) {
		this.adminPhone = adminPhone;
	}

	/**
	 * 전화번호을 가져옵니다..
	 * 
	 * @return 전화번호
	 */
	public String getAdminPhone() {
		return this.adminPhone;
	}

	/**
	 * 등급을 설정합니다..
	 * 
	 * @param adminRating
	 *            등급
	 */
	public void setAdminRating(String adminRating) {
		this.adminRating = adminRating;
	}

	/**
	 * 등급을 가져옵니다..
	 * 
	 * @return 등급
	 */
	public String getAdminRating() {
		return this.adminRating;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adminSeq == null) ? 0 : adminSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Admin other = (Admin) obj;
		if (adminSeq == null) {
			if (other.adminSeq != null) {
				return false;
			}
		} else if (!adminSeq.equals(other.adminSeq)) {
			return false;
		}
		return true;
	}

}
