package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 장바구니 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Basket implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 장바구니번호. */
	private Integer basketSeq;

	/** 상품수량. */
	private String basketQuantity;

	/**
	 * 생성자.
	 */
	public Basket() {
	}
	
	

	public Basket(Integer basketSeq, String basketQuantity) {
		super();
		this.basketSeq = basketSeq;
		this.basketQuantity = basketQuantity;
	}



	/**
	 * 장바구니번호을 설정합니다..
	 * 
	 * @param basketSeq
	 *            장바구니번호
	 */
	public void setBasketSeq(Integer basketSeq) {
		this.basketSeq = basketSeq;
	}

	/**
	 * 장바구니번호을 가져옵니다..
	 * 
	 * @return 장바구니번호
	 */
	public Integer getBasketSeq() {
		return this.basketSeq;
	}

	/**
	 * 상품수량을 설정합니다..
	 * 
	 * @param basketQuantity
	 *            상품수량
	 */
	public void setBasketQuantity(String basketQuantity) {
		this.basketQuantity = basketQuantity;
	}

	/**
	 * 상품수량을 가져옵니다..
	 * 
	 * @return 상품수량
	 */
	public String getBasketQuantity() {
		return this.basketQuantity;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((basketSeq == null) ? 0 : basketSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Basket other = (Basket) obj;
		if (basketSeq == null) {
			if (other.basketSeq != null) {
				return false;
			}
		} else if (!basketSeq.equals(other.basketSeq)) {
			return false;
		}
		return true;
	}

}
