package kosta1200.todayroom.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Board implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 글번호. */
	private Integer boardSeq;

	/** 제목. */
	private String boardTitle;

	/** 내용. */
	private String boardContent;

	/** 날짜. */
	private Date boardDate;

	/** 사진이름. */
	private String boardPicture;

	/** 썸네일이름. */
	private String boardThumbnail;

	/** 분류. */
	private String boardClassification;

	/** 조회수. */
	private String boardViews;

	/** 스크랩수. */
	private String boardScarps;

	/**
	 * 생성자.
	 */
	public Board() {
	}
	
	

	public Board(Integer boardSeq, String boardTitle, String boardContent, Date boardDate, String boardPicture,
			String boardThumbnail, String boardClassification, String boardViews, String boardScarps) {
		super();
		this.boardSeq = boardSeq;
		this.boardTitle = boardTitle;
		this.boardContent = boardContent;
		this.boardDate = boardDate;
		this.boardPicture = boardPicture;
		this.boardThumbnail = boardThumbnail;
		this.boardClassification = boardClassification;
		this.boardViews = boardViews;
		this.boardScarps = boardScarps;
	}



	/**
	 * 글번호을 설정합니다..
	 * 
	 * @param boardSeq
	 *            글번호
	 */
	public void setBoardSeq(Integer boardSeq) {
		this.boardSeq = boardSeq;
	}

	/**
	 * 글번호을 가져옵니다..
	 * 
	 * @return 글번호
	 */
	public Integer getBoardSeq() {
		return this.boardSeq;
	}

	/**
	 * 제목을 설정합니다..
	 * 
	 * @param boardTitle
	 *            제목
	 */
	public void setBoardTitle(String boardTitle) {
		this.boardTitle = boardTitle;
	}

	/**
	 * 제목을 가져옵니다..
	 * 
	 * @return 제목
	 */
	public String getBoardTitle() {
		return this.boardTitle;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param boardContent
	 *            내용
	 */
	public void setBoardContent(String boardContent) {
		this.boardContent = boardContent;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getBoardContent() {
		return this.boardContent;
	}

	/**
	 * 날짜을 설정합니다..
	 * 
	 * @param boardDate
	 *            날짜
	 */
	public void setBoardDate(Date boardDate) {
		this.boardDate = boardDate;
	}

	/**
	 * 날짜을 가져옵니다..
	 * 
	 * @return 날짜
	 */
	public Date getBoardDate() {
		return this.boardDate;
	}

	/**
	 * 사진이름을 설정합니다..
	 * 
	 * @param boardPicture
	 *            사진이름
	 */
	public void setBoardPicture(String boardPicture) {
		this.boardPicture = boardPicture;
	}

	/**
	 * 사진이름을 가져옵니다..
	 * 
	 * @return 사진이름
	 */
	public String getBoardPicture() {
		return this.boardPicture;
	}

	/**
	 * 썸네일이름을 설정합니다..
	 * 
	 * @param boardThumbnail
	 *            썸네일이름
	 */
	public void setBoardThumbnail(String boardThumbnail) {
		this.boardThumbnail = boardThumbnail;
	}

	/**
	 * 썸네일이름을 가져옵니다..
	 * 
	 * @return 썸네일이름
	 */
	public String getBoardThumbnail() {
		return this.boardThumbnail;
	}

	/**
	 * 분류을 설정합니다..
	 * 
	 * @param boardClassification
	 *            분류
	 */
	public void setBoardClassification(String boardClassification) {
		this.boardClassification = boardClassification;
	}

	/**
	 * 분류을 가져옵니다..
	 * 
	 * @return 분류
	 */
	public String getBoardClassification() {
		return this.boardClassification;
	}

	/**
	 * 조회수을 설정합니다..
	 * 
	 * @param boardViews
	 *            조회수
	 */
	public void setBoardViews(String boardViews) {
		this.boardViews = boardViews;
	}

	/**
	 * 조회수을 가져옵니다..
	 * 
	 * @return 조회수
	 */
	public String getBoardViews() {
		return this.boardViews;
	}

	/**
	 * 스크랩수을 설정합니다..
	 * 
	 * @param boardScarps
	 *            스크랩수
	 */
	public void setBoardScarps(String boardScarps) {
		this.boardScarps = boardScarps;
	}

	/**
	 * 스크랩수을 가져옵니다..
	 * 
	 * @return 스크랩수
	 */
	public String getBoardScarps() {
		return this.boardScarps;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((boardSeq == null) ? 0 : boardSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Board other = (Board) obj;
		if (boardSeq == null) {
			if (other.boardSeq != null) {
				return false;
			}
		} else if (!boardSeq.equals(other.boardSeq)) {
			return false;
		}
		return true;
	}

}
