package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Comments implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글번호. */
	private Integer commentsSeq;

	/** 내용. */
	private String commentsContent;

	/** 사진이름. */
	private String commentsPicture;

	/**
	 * 생성자.
	 */
	public Comments() {
	}
	

	public Comments(Integer commentsSeq, String commentsContent, String commentsPicture) {
		super();
		this.commentsSeq = commentsSeq;
		this.commentsContent = commentsContent;
		this.commentsPicture = commentsPicture;
	}


	/**
	 * 댓글번호을 설정합니다..
	 * 
	 * @param commentsSeq
	 *            댓글번호
	 */
	public void setCommentsSeq(Integer commentsSeq) {
		this.commentsSeq = commentsSeq;
	}

	/**
	 * 댓글번호을 가져옵니다..
	 * 
	 * @return 댓글번호
	 */
	public Integer getCommentsSeq() {
		return this.commentsSeq;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param commentsContent
	 *            내용
	 */
	public void setCommentsContent(String commentsContent) {
		this.commentsContent = commentsContent;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getCommentsContent() {
		return this.commentsContent;
	}

	/**
	 * 사진이름을 설정합니다..
	 * 
	 * @param commentsPicture
	 *            사진이름
	 */
	public void setCommentsPicture(String commentsPicture) {
		this.commentsPicture = commentsPicture;
	}

	/**
	 * 사진이름을 가져옵니다..
	 * 
	 * @return 사진이름
	 */
	public String getCommentsPicture() {
		return this.commentsPicture;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commentsSeq == null) ? 0 : commentsSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Comments other = (Comments) obj;
		if (commentsSeq == null) {
			if (other.commentsSeq != null) {
				return false;
			}
		} else if (!commentsSeq.equals(other.commentsSeq)) {
			return false;
		}
		return true;
	}

}
