package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 시공신청 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Const implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 시공신청번호. */
	private Integer constSeq;

	/** 공간. */
	private String constSpace;

	/** 스타일. */
	private String constStyle;

	/** 컬러. */
	private String constColor;

	/** 예산. */
	private String constBudget;

	/**
	 * 생성자.
	 */
	public Const() {
	}
	

	public Const(Integer constSeq, String constSpace, String constStyle, String constColor, String constBudget) {
		super();
		this.constSeq = constSeq;
		this.constSpace = constSpace;
		this.constStyle = constStyle;
		this.constColor = constColor;
		this.constBudget = constBudget;
	}


	/**
	 * 시공신청번호을 설정합니다..
	 * 
	 * @param constSeq
	 *            시공신청번호
	 */
	public void setConstSeq(Integer constSeq) {
		this.constSeq = constSeq;
	}

	/**
	 * 시공신청번호을 가져옵니다..
	 * 
	 * @return 시공신청번호
	 */
	public Integer getConstSeq() {
		return this.constSeq;
	}

	/**
	 * 공간을 설정합니다..
	 * 
	 * @param constSpace
	 *            공간
	 */
	public void setConstSpace(String constSpace) {
		this.constSpace = constSpace;
	}

	/**
	 * 공간을 가져옵니다..
	 * 
	 * @return 공간
	 */
	public String getConstSpace() {
		return this.constSpace;
	}

	/**
	 * 스타일을 설정합니다..
	 * 
	 * @param constStyle
	 *            스타일
	 */
	public void setConstStyle(String constStyle) {
		this.constStyle = constStyle;
	}

	/**
	 * 스타일을 가져옵니다..
	 * 
	 * @return 스타일
	 */
	public String getConstStyle() {
		return this.constStyle;
	}

	/**
	 * 컬러을 설정합니다..
	 * 
	 * @param constColor
	 *            컬러
	 */
	public void setConstColor(String constColor) {
		this.constColor = constColor;
	}

	/**
	 * 컬러을 가져옵니다..
	 * 
	 * @return 컬러
	 */
	public String getConstColor() {
		return this.constColor;
	}

	/**
	 * 예산을 설정합니다..
	 * 
	 * @param constBudget
	 *            예산
	 */
	public void setConstBudget(String constBudget) {
		this.constBudget = constBudget;
	}

	/**
	 * 예산을 가져옵니다..
	 * 
	 * @return 예산
	 */
	public String getConstBudget() {
		return this.constBudget;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((constSeq == null) ? 0 : constSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Const other = (Const) obj;
		if (constSeq == null) {
			if (other.constSeq != null) {
				return false;
			}
		} else if (!constSeq.equals(other.constSeq)) {
			return false;
		}
		return true;
	}

}
