package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 인테리어시공업체(신청서) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Contractor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 인테리어시공업체번호. */
	private Integer contractorSeq;

	/** 상호명. */
	private String contractorBname;

	/** 사업자대표명. */
	private String contractorName;

	/** 사업자주소. */
	private String contractorAddress;

	/**
	 * 생성자.
	 */
	public Contractor() {
	}
	

	public Contractor(Integer contractorSeq, String contractorBname, String contractorName, String contractorAddress) {
		super();
		this.contractorSeq = contractorSeq;
		this.contractorBname = contractorBname;
		this.contractorName = contractorName;
		this.contractorAddress = contractorAddress;
	}


	/**
	 * 인테리어시공업체번호을 설정합니다..
	 * 
	 * @param contractorSeq
	 *            인테리어시공업체번호
	 */
	public void setContractorSeq(Integer contractorSeq) {
		this.contractorSeq = contractorSeq;
	}

	/**
	 * 인테리어시공업체번호을 가져옵니다..
	 * 
	 * @return 인테리어시공업체번호
	 */
	public Integer getContractorSeq() {
		return this.contractorSeq;
	}

	/**
	 * 상호명을 설정합니다..
	 * 
	 * @param contractorBname
	 *            상호명
	 */
	public void setContractorBname(String contractorBname) {
		this.contractorBname = contractorBname;
	}

	/**
	 * 상호명을 가져옵니다..
	 * 
	 * @return 상호명
	 */
	public String getContractorBname() {
		return this.contractorBname;
	}

	/**
	 * 사업자대표명을 설정합니다..
	 * 
	 * @param contractorName
	 *            사업자대표명
	 */
	public void setContractorName(String contractorName) {
		this.contractorName = contractorName;
	}

	/**
	 * 사업자대표명을 가져옵니다..
	 * 
	 * @return 사업자대표명
	 */
	public String getContractorName() {
		return this.contractorName;
	}

	/**
	 * 사업자주소을 설정합니다..
	 * 
	 * @param contractorAddress
	 *            사업자주소
	 */
	public void setContractorAddress(String contractorAddress) {
		this.contractorAddress = contractorAddress;
	}

	/**
	 * 사업자주소을 가져옵니다..
	 * 
	 * @return 사업자주소
	 */
	public String getContractorAddress() {
		return this.contractorAddress;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((contractorSeq == null) ? 0 : contractorSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Contractor other = (Contractor) obj;
		if (contractorSeq == null) {
			if (other.contractorSeq != null) {
				return false;
			}
		} else if (!contractorSeq.equals(other.contractorSeq)) {
			return false;
		}
		return true;
	}

}
