package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * FAQ 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Faq implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** FAQ번호. */
	private Integer faqSeq;

	/** 분류. */
	private String faqClassification;

	/** 제목. */
	private String faqTitle;

	/** 내용. */
	private String faqContent;

	/**
	 * 생성자.
	 */
	public Faq() {
	}
	

	public Faq(Integer faqSeq, String faqClassification, String faqTitle, String faqContent) {
		super();
		this.faqSeq = faqSeq;
		this.faqClassification = faqClassification;
		this.faqTitle = faqTitle;
		this.faqContent = faqContent;
	}


	/**
	 * FAQ번호을 설정합니다..
	 * 
	 * @param faqSeq
	 *            FAQ번호
	 */
	public void setFaqSeq(Integer faqSeq) {
		this.faqSeq = faqSeq;
	}

	/**
	 * FAQ번호을 가져옵니다..
	 * 
	 * @return FAQ번호
	 */
	public Integer getFaqSeq() {
		return this.faqSeq;
	}

	/**
	 * 분류을 설정합니다..
	 * 
	 * @param faqClassification
	 *            분류
	 */
	public void setFaqClassification(String faqClassification) {
		this.faqClassification = faqClassification;
	}

	/**
	 * 분류을 가져옵니다..
	 * 
	 * @return 분류
	 */
	public String getFaqClassification() {
		return this.faqClassification;
	}

	/**
	 * 제목을 설정합니다..
	 * 
	 * @param faqTitle
	 *            제목
	 */
	public void setFaqTitle(String faqTitle) {
		this.faqTitle = faqTitle;
	}

	/**
	 * 제목을 가져옵니다..
	 * 
	 * @return 제목
	 */
	public String getFaqTitle() {
		return this.faqTitle;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param faqContent
	 *            내용
	 */
	public void setFaqContent(String faqContent) {
		this.faqContent = faqContent;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getFaqContent() {
		return this.faqContent;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((faqSeq == null) ? 0 : faqSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Faq other = (Faq) obj;
		if (faqSeq == null) {
			if (other.faqSeq != null) {
				return false;
			}
		} else if (!faqSeq.equals(other.faqSeq)) {
			return false;
		}
		return true;
	}

}
