package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 노하우 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Knowhow implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 스타일. */
	private String knowhowStyle;

	/**
	 * 생성자.
	 */
	public Knowhow() {
	}
	

	public Knowhow(String knowhowStyle) {
		super();
		this.knowhowStyle = knowhowStyle;
	}


	/**
	 * 스타일을 설정합니다..
	 * 
	 * @param knowhowStyle
	 *            스타일
	 */
	public void setKnowhowStyle(String knowhowStyle) {
		this.knowhowStyle = knowhowStyle;
	}

	/**
	 * 스타일을 가져옵니다..
	 * 
	 * @return 스타일
	 */
	public String getKnowhowStyle() {
		return this.knowhowStyle;
	}


}
