package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원번호. */
	private Integer memberSeq;

	/** 아이디. */
	private String memberId;

	/** 별명. */
	private String memberNickname;

	/** 이름. */
	private String memberName;

	/** 주소. */
	private String memberAddress;

	/** 핸드폰번호. */
	private String memberPhone;

	/** e-mail. */
	private String memberEmail;

	/** 회원등급. */
	private String memberRating;

	/** 비밀번호. */
	private String memberPassword;

	/** 팔로우수. */
	private String memberFollows;

	/**
	 * 생성자.
	 */
	public Member() {
	}
	

	
	
	public Member(Integer memberSeq, String memberId, String memberNickname, String memberName, String memberAddress,
			String memberPhone, String memberEmail, String memberRating, String memberPassword, String memberFollows) {
		super();
		this.memberSeq = memberSeq;
		this.memberId = memberId;
		this.memberNickname = memberNickname;
		this.memberName = memberName;
		this.memberAddress = memberAddress;
		this.memberPhone = memberPhone;
		this.memberEmail = memberEmail;
		this.memberRating = memberRating;
		this.memberPassword = memberPassword;
		this.memberFollows = memberFollows;
	}




	/**
	 * 회원번호을 설정합니다..
	 * 
	 * @param memberSeq
	 *            회원번호
	 */
	public void setMemberSeq(Integer memberSeq) {
		this.memberSeq = memberSeq;
	}

	/**
	 * 회원번호을 가져옵니다..
	 * 
	 * @return 회원번호
	 */
	public Integer getMemberSeq() {
		return this.memberSeq;
	}

	/**
	 * 아이디을 설정합니다..
	 * 
	 * @param memberId
	 *            아이디
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * 아이디을 가져옵니다..
	 * 
	 * @return 아이디
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * 별명을 설정합니다..
	 * 
	 * @param memberNickname
	 *            별명
	 */
	public void setMemberNickname(String memberNickname) {
		this.memberNickname = memberNickname;
	}

	/**
	 * 별명을 가져옵니다..
	 * 
	 * @return 별명
	 */
	public String getMemberNickname() {
		return this.memberNickname;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param memberName
	 *            이름
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getMemberName() {
		return this.memberName;
	}

	/**
	 * 주소을 설정합니다..
	 * 
	 * @param memberAddress
	 *            주소
	 */
	public void setMemberAddress(String memberAddress) {
		this.memberAddress = memberAddress;
	}

	/**
	 * 주소을 가져옵니다..
	 * 
	 * @return 주소
	 */
	public String getMemberAddress() {
		return this.memberAddress;
	}

	/**
	 * 핸드폰번호을 설정합니다..
	 * 
	 * @param memberPhone
	 *            핸드폰번호
	 */
	public void setMemberPhone(String memberPhone) {
		this.memberPhone = memberPhone;
	}

	/**
	 * 핸드폰번호을 가져옵니다..
	 * 
	 * @return 핸드폰번호
	 */
	public String getMemberPhone() {
		return this.memberPhone;
	}

	/**
	 * e-mail을 설정합니다..
	 * 
	 * @param memberEmail
	 *            e-mail
	 */
	public void setMemberEmail(String memberEmail) {
		this.memberEmail = memberEmail;
	}

	/**
	 * e-mail을 가져옵니다..
	 * 
	 * @return e-mail
	 */
	public String getMemberEmail() {
		return this.memberEmail;
	}

	/**
	 * 회원등급을 설정합니다..
	 * 
	 * @param memberRating
	 *            회원등급
	 */
	public void setMemberRating(String memberRating) {
		this.memberRating = memberRating;
	}

	/**
	 * 회원등급을 가져옵니다..
	 * 
	 * @return 회원등급
	 */
	public String getMemberRating() {
		return this.memberRating;
	}

	/**
	 * 비밀번호을 설정합니다..
	 * 
	 * @param memberPassword
	 *            비밀번호
	 */
	public void setMemberPassword(String memberPassword) {
		this.memberPassword = memberPassword;
	}

	/**
	 * 비밀번호을 가져옵니다..
	 * 
	 * @return 비밀번호
	 */
	public String getMemberPassword() {
		return this.memberPassword;
	}

	/**
	 * 팔로우수을 설정합니다..
	 * 
	 * @param memberFollows
	 *            팔로우수
	 */
	public void setMemberFollows(String memberFollows) {
		this.memberFollows = memberFollows;
	}

	/**
	 * 팔로우수을 가져옵니다..
	 * 
	 * @return 팔로우수
	 */
	public String getMemberFollows() {
		return this.memberFollows;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((memberSeq == null) ? 0 : memberSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Member other = (Member) obj;
		if (memberSeq == null) {
			if (other.memberSeq != null) {
				return false;
			}
		} else if (!memberSeq.equals(other.memberSeq)) {
			return false;
		}
		return true;
	}

}
