package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 일대일문의 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class OneInquiry implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사이트문의번호. */
	private Integer oiSeq;

	/** 문의제목. */
	private String oiTitle;

	/** 문의내용. */
	private String oiContent;

	/** 답변내용. */
	private String oiAnswer;

	/**
	 * 생성자.
	 */
	public OneInquiry() {
	}
	

	public OneInquiry(Integer oiSeq, String oiTitle, String oiContent, String oiAnswer) {
		super();
		this.oiSeq = oiSeq;
		this.oiTitle = oiTitle;
		this.oiContent = oiContent;
		this.oiAnswer = oiAnswer;
	}


	/**
	 * 사이트문의번호을 설정합니다..
	 * 
	 * @param oiSeq
	 *            사이트문의번호
	 */
	public void setOiSeq(Integer oiSeq) {
		this.oiSeq = oiSeq;
	}

	/**
	 * 사이트문의번호을 가져옵니다..
	 * 
	 * @return 사이트문의번호
	 */
	public Integer getOiSeq() {
		return this.oiSeq;
	}

	/**
	 * 문의제목을 설정합니다..
	 * 
	 * @param oiTitle
	 *            문의제목
	 */
	public void setOiTitle(String oiTitle) {
		this.oiTitle = oiTitle;
	}

	/**
	 * 문의제목을 가져옵니다..
	 * 
	 * @return 문의제목
	 */
	public String getOiTitle() {
		return this.oiTitle;
	}

	/**
	 * 문의내용을 설정합니다..
	 * 
	 * @param oiContent
	 *            문의내용
	 */
	public void setOiContent(String oiContent) {
		this.oiContent = oiContent;
	}

	/**
	 * 문의내용을 가져옵니다..
	 * 
	 * @return 문의내용
	 */
	public String getOiContent() {
		return this.oiContent;
	}

	/**
	 * 답변내용을 설정합니다..
	 * 
	 * @param oiAnswer
	 *            답변내용
	 */
	public void setOiAnswer(String oiAnswer) {
		this.oiAnswer = oiAnswer;
	}

	/**
	 * 답변내용을 가져옵니다..
	 * 
	 * @return 답변내용
	 */
	public String getOiAnswer() {
		return this.oiAnswer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((oiSeq == null) ? 0 : oiSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		OneInquiry other = (OneInquiry) obj;
		if (oiSeq == null) {
			if (other.oiSeq != null) {
				return false;
			}
		} else if (!oiSeq.equals(other.oiSeq)) {
			return false;
		}
		return true;
	}

}
