package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 상품문의 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ProductInquiry implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 상품문의번호. */
	private Integer piSeq;

	/** 문의유형. */
	private String piType;

	/** 문의내용. */
	private String piContent;

	/** 답변내용. */
	private String piAnswer;

	/**
	 * 생성자.
	 */
	public ProductInquiry() {
	}
	

	public ProductInquiry(Integer piSeq, String piType, String piContent, String piAnswer) {
		super();
		this.piSeq = piSeq;
		this.piType = piType;
		this.piContent = piContent;
		this.piAnswer = piAnswer;
	}


	/**
	 * 상품문의번호을 설정합니다..
	 * 
	 * @param piSeq
	 *            상품문의번호
	 */
	public void setPiSeq(Integer piSeq) {
		this.piSeq = piSeq;
	}

	/**
	 * 상품문의번호을 가져옵니다..
	 * 
	 * @return 상품문의번호
	 */
	public Integer getPiSeq() {
		return this.piSeq;
	}

	/**
	 * 문의유형을 설정합니다..
	 * 
	 * @param piType
	 *            문의유형
	 */
	public void setPiType(String piType) {
		this.piType = piType;
	}

	/**
	 * 문의유형을 가져옵니다..
	 * 
	 * @return 문의유형
	 */
	public String getPiType() {
		return this.piType;
	}

	/**
	 * 문의내용을 설정합니다..
	 * 
	 * @param piContent
	 *            문의내용
	 */
	public void setPiContent(String piContent) {
		this.piContent = piContent;
	}

	/**
	 * 문의내용을 가져옵니다..
	 * 
	 * @return 문의내용
	 */
	public String getPiContent() {
		return this.piContent;
	}

	/**
	 * 답변내용을 설정합니다..
	 * 
	 * @param piAnswer
	 *            답변내용
	 */
	public void setPiAnswer(String piAnswer) {
		this.piAnswer = piAnswer;
	}

	/**
	 * 답변내용을 가져옵니다..
	 * 
	 * @return 답변내용
	 */
	public String getPiAnswer() {
		return this.piAnswer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((piSeq == null) ? 0 : piSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ProductInquiry other = (ProductInquiry) obj;
		if (piSeq == null) {
			if (other.piSeq != null) {
				return false;
			}
		} else if (!piSeq.equals(other.piSeq)) {
			return false;
		}
		return true;
	}

}
