package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 상품 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 상품번호. */
	private Integer productSeq;

	/** 상품명. */
	private String productName;

	/** 가격. */
	private Integer productPrice;

	/** 종류1. */
	private String productLcategory;

	/** 종류2. */
	private String productScategory;

	/** 배송비. */
	private Integer productDlvchr;

	private Integer boardSeq;
	
	public Integer getBoardSeq() {
		return boardSeq;
	}


	public void setBoardSeq(Integer boardSeq) {
		this.boardSeq = boardSeq;
	}


	/**
	 * 생성자.
	 */
	public Product() {
	}
	

	public Product(Integer productSeq, String productName, Integer productPrice, String productLcategory,
			String productScategory, Integer productDlvchr) {
		super();
		this.productSeq = productSeq;
		this.productName = productName;
		this.productPrice = productPrice;
		this.productLcategory = productLcategory;
		this.productScategory = productScategory;
		this.productDlvchr = productDlvchr;
	}


	/**
	 * 상품번호을 설정합니다..
	 * 
	 * @param productSeq
	 *            상품번호
	 */
	public void setProductSeq(Integer productSeq) {
		this.productSeq = productSeq;
	}

	/**
	 * 상품번호을 가져옵니다..
	 * 
	 * @return 상품번호
	 */
	public Integer getProductSeq() {
		return this.productSeq;
	}

	/**
	 * 상품명을 설정합니다..
	 * 
	 * @param productName
	 *            상품명
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * 상품명을 가져옵니다..
	 * 
	 * @return 상품명
	 */
	public String getProductName() {
		return this.productName;
	}

	/**
	 * 가격을 설정합니다..
	 * 
	 * @param productPrice
	 *            가격
	 */
	public void setProductPrice(Integer productPrice) {
		this.productPrice = productPrice;
	}

	/**
	 * 가격을 가져옵니다..
	 * 
	 * @return 가격
	 */
	public Integer getProductPrice() {
		return this.productPrice;
	}

	/**
	 * 종류1을 설정합니다..
	 * 
	 * @param productLcategory
	 *            종류1
	 */
	public void setProductLcategory(String productLcategory) {
		this.productLcategory = productLcategory;
	}

	/**
	 * 종류1을 가져옵니다..
	 * 
	 * @return 종류1
	 */
	public String getProductLcategory() {
		return this.productLcategory;
	}

	/**
	 * 종류2을 설정합니다..
	 * 
	 * @param productScategory
	 *            종류2
	 */
	public void setProductScategory(String productScategory) {
		this.productScategory = productScategory;
	}

	/**
	 * 종류2을 가져옵니다..
	 * 
	 * @return 종류2
	 */
	public String getProductScategory() {
		return this.productScategory;
	}

	/**
	 * 배송비을 설정합니다..
	 * 
	 * @param productDlvchr
	 *            배송비
	 */
	public void setProductDlvchr(Integer productDlvchr) {
		this.productDlvchr = productDlvchr;
	}

	/**
	 * 배송비을 가져옵니다..
	 * 
	 * @return 배송비
	 */
	public Integer getProductDlvchr() {
		return this.productDlvchr;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productSeq == null) ? 0 : productSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (productSeq == null) {
			if (other.productSeq != null) {
				return false;
			}
		} else if (!productSeq.equals(other.productSeq)) {
			return false;
		}
		return true;
	}

}
