package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 신고 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Report implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 신고번호. */
	private Integer reportSeq;

	/** 신고사유. */
	private String reportReason;

	/**
	 * 생성자.
	 */
	public Report() {
	}
	

	public Report(Integer reportSeq, String reportReason) {
		super();
		this.reportSeq = reportSeq;
		this.reportReason = reportReason;
	}


	/**
	 * 신고번호을 설정합니다..
	 * 
	 * @param reportSeq
	 *            신고번호
	 */
	public void setReportSeq(Integer reportSeq) {
		this.reportSeq = reportSeq;
	}

	/**
	 * 신고번호을 가져옵니다..
	 * 
	 * @return 신고번호
	 */
	public Integer getReportSeq() {
		return this.reportSeq;
	}

	/**
	 * 신고사유을 설정합니다..
	 * 
	 * @param reportReason
	 *            신고사유
	 */
	public void setReportReason(String reportReason) {
		this.reportReason = reportReason;
	}

	/**
	 * 신고사유을 가져옵니다..
	 * 
	 * @return 신고사유
	 */
	public String getReportReason() {
		return this.reportReason;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reportSeq == null) ? 0 : reportSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Report other = (Report) obj;
		if (reportSeq == null) {
			if (other.reportSeq != null) {
				return false;
			}
		} else if (!reportSeq.equals(other.reportSeq)) {
			return false;
		}
		return true;
	}

}
