package kosta1200.todayroom.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 리뷰 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Review implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 리뷰번호. */
	private Integer reviewSeq;

	/** 날짜. */
	private Date reviewDate;

	/** 평점. */
	private String reviewRating;

	/** 내용. */
	private String reviewContent;

	/** 사진이름. */
	private String reviewPicture;

	/**
	 * 생성자.
	 */
	public Review() {
	}
	

	public Review(Integer reviewSeq, Date reviewDate, String reviewRating, String reviewContent, String reviewPicture) {
		super();
		this.reviewSeq = reviewSeq;
		this.reviewDate = reviewDate;
		this.reviewRating = reviewRating;
		this.reviewContent = reviewContent;
		this.reviewPicture = reviewPicture;
	}


	/**
	 * 리뷰번호을 설정합니다..
	 * 
	 * @param reviewSeq
	 *            리뷰번호
	 */
	public void setReviewSeq(Integer reviewSeq) {
		this.reviewSeq = reviewSeq;
	}

	/**
	 * 리뷰번호을 가져옵니다..
	 * 
	 * @return 리뷰번호
	 */
	public Integer getReviewSeq() {
		return this.reviewSeq;
	}

	/**
	 * 날짜을 설정합니다..
	 * 
	 * @param reviewDate
	 *            날짜
	 */
	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	/**
	 * 날짜을 가져옵니다..
	 * 
	 * @return 날짜
	 */
	public Date getReviewDate() {
		return this.reviewDate;
	}

	/**
	 * 평점을 설정합니다..
	 * 
	 * @param reviewRating
	 *            평점
	 */
	public void setReviewRating(String reviewRating) {
		this.reviewRating = reviewRating;
	}

	/**
	 * 평점을 가져옵니다..
	 * 
	 * @return 평점
	 */
	public String getReviewRating() {
		return this.reviewRating;
	}

	/**
	 * 내용을 설정합니다..
	 * 
	 * @param reviewContent
	 *            내용
	 */
	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}

	/**
	 * 내용을 가져옵니다..
	 * 
	 * @return 내용
	 */
	public String getReviewContent() {
		return this.reviewContent;
	}

	/**
	 * 사진이름을 설정합니다..
	 * 
	 * @param reviewPicture
	 *            사진이름
	 */
	public void setReviewPicture(String reviewPicture) {
		this.reviewPicture = reviewPicture;
	}

	/**
	 * 사진이름을 가져옵니다..
	 * 
	 * @return 사진이름
	 */
	public String getReviewPicture() {
		return this.reviewPicture;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((reviewSeq == null) ? 0 : reviewSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Review other = (Review) obj;
		if (reviewSeq == null) {
			if (other.reviewSeq != null) {
				return false;
			}
		} else if (!reviewSeq.equals(other.reviewSeq)) {
			return false;
		}
		return true;
	}

}
