package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 방들이 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Roomwarming implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 작업(분류). */
	private String roomwarmingClassification;

	/** 공간. */
	private String roomwarmingSpace;

	/** 스타일. */
	private String roomwarmingStyle;

	/** 컬러. */
	private String roomwarmingColor;

	/** 예산. */
	private String roomwarmingBudget;

	/**
	 * 생성자.
	 */
	public Roomwarming() {
	}
	

	public Roomwarming(String roomwarmingClassification, String roomwarmingSpace, String roomwarmingStyle,
			String roomwarmingColor, String roomwarmingBudget) {
		super();
		this.roomwarmingClassification = roomwarmingClassification;
		this.roomwarmingSpace = roomwarmingSpace;
		this.roomwarmingStyle = roomwarmingStyle;
		this.roomwarmingColor = roomwarmingColor;
		this.roomwarmingBudget = roomwarmingBudget;
	}


	/**
	 * 작업(분류)을 설정합니다..
	 * 
	 * @param roomwarmingClassification
	 *            작업(분류)
	 */
	public void setRoomwarmingClassification(String roomwarmingClassification) {
		this.roomwarmingClassification = roomwarmingClassification;
	}

	/**
	 * 작업(분류)을 가져옵니다..
	 * 
	 * @return 작업(분류)
	 */
	public String getRoomwarmingClassification() {
		return this.roomwarmingClassification;
	}

	/**
	 * 공간을 설정합니다..
	 * 
	 * @param roomwarmingSpace
	 *            공간
	 */
	public void setRoomwarmingSpace(String roomwarmingSpace) {
		this.roomwarmingSpace = roomwarmingSpace;
	}

	/**
	 * 공간을 가져옵니다..
	 * 
	 * @return 공간
	 */
	public String getRoomwarmingSpace() {
		return this.roomwarmingSpace;
	}

	/**
	 * 스타일을 설정합니다..
	 * 
	 * @param roomwarmingStyle
	 *            스타일
	 */
	public void setRoomwarmingStyle(String roomwarmingStyle) {
		this.roomwarmingStyle = roomwarmingStyle;
	}

	/**
	 * 스타일을 가져옵니다..
	 * 
	 * @return 스타일
	 */
	public String getRoomwarmingStyle() {
		return this.roomwarmingStyle;
	}

	/**
	 * 컬러을 설정합니다..
	 * 
	 * @param roomwarmingColor
	 *            컬러
	 */
	public void setRoomwarmingColor(String roomwarmingColor) {
		this.roomwarmingColor = roomwarmingColor;
	}

	/**
	 * 컬러을 가져옵니다..
	 * 
	 * @return 컬러
	 */
	public String getRoomwarmingColor() {
		return this.roomwarmingColor;
	}

	/**
	 * 예산을 설정합니다..
	 * 
	 * @param roomwarmingBudget
	 *            예산
	 */
	public void setRoomwarmingBudget(String roomwarmingBudget) {
		this.roomwarmingBudget = roomwarmingBudget;
	}

	/**
	 * 예산을 가져옵니다..
	 * 
	 * @return 예산
	 */
	public String getRoomwarmingBudget() {
		return this.roomwarmingBudget;
	}


}
