package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * ½ºÅ©·¦ ¸ðµ¨ Å¬·¡½º.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Scrap implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ½ºÅ©·¦¹øÈ£. */
	private Integer scrapSeq;

	/**
	 * »ý¼ºÀÚ.
	 */
	public Scrap() {
	}
	

	public Scrap(Integer scrapSeq) {
		super();
		this.scrapSeq = scrapSeq;
	}


	/**
	 * ½ºÅ©·¦¹øÈ£À» ¼³Á¤ÇÕ´Ï´Ù..
	 * 
	 * @param scrapSeq
	 *            ½ºÅ©·¦¹øÈ£
	 */
	public void setScrapSeq(Integer scrapSeq) {
		this.scrapSeq = scrapSeq;
	}

	/**
	 * ½ºÅ©·¦¹øÈ£À» °¡Á®¿É´Ï´Ù..
	 * 
	 * @return ½ºÅ©·¦¹øÈ£
	 */
	public Integer getScrapSeq() {
		return this.scrapSeq;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((scrapSeq == null) ? 0 : scrapSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Scrap other = (Scrap) obj;
		if (scrapSeq == null) {
			if (other.scrapSeq != null) {
				return false;
			}
		} else if (!scrapSeq.equals(other.scrapSeq)) {
			return false;
		}
		return true;
	}

}
