package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 배송지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shipping implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 배송지번호. */
	private Integer shippingSeq;

	/** 배송지명. */
	private String shippingName;

	/** 받는분. */
	private String shippingRecipients;

	/** 주소. */
	private String shippingAddress;

	/** 전화번호. */
	private String shippingPhone;

	/**
	 * 생성자.
	 */
	public Shipping() {
	}
	

	public Shipping(Integer shippingSeq, String shippingName, String shippingRecipients, String shippingAddress,
			String shippingPhone) {
		super();
		this.shippingSeq = shippingSeq;
		this.shippingName = shippingName;
		this.shippingRecipients = shippingRecipients;
		this.shippingAddress = shippingAddress;
		this.shippingPhone = shippingPhone;
	}


	/**
	 * 배송지번호을 설정합니다..
	 * 
	 * @param shippingSeq
	 *            배송지번호
	 */
	public void setShippingSeq(Integer shippingSeq) {
		this.shippingSeq = shippingSeq;
	}

	/**
	 * 배송지번호을 가져옵니다..
	 * 
	 * @return 배송지번호
	 */
	public Integer getShippingSeq() {
		return this.shippingSeq;
	}

	/**
	 * 배송지명을 설정합니다..
	 * 
	 * @param shippingName
	 *            배송지명
	 */
	public void setShippingName(String shippingName) {
		this.shippingName = shippingName;
	}

	/**
	 * 배송지명을 가져옵니다..
	 * 
	 * @return 배송지명
	 */
	public String getShippingName() {
		return this.shippingName;
	}

	/**
	 * 받는분을 설정합니다..
	 * 
	 * @param shippingRecipients
	 *            받는분
	 */
	public void setShippingRecipients(String shippingRecipients) {
		this.shippingRecipients = shippingRecipients;
	}

	/**
	 * 받는분을 가져옵니다..
	 * 
	 * @return 받는분
	 */
	public String getShippingRecipients() {
		return this.shippingRecipients;
	}

	/**
	 * 주소을 설정합니다..
	 * 
	 * @param shippingAddress
	 *            주소
	 */
	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	/**
	 * 주소을 가져옵니다..
	 * 
	 * @return 주소
	 */
	public String getShippingAddress() {
		return this.shippingAddress;
	}

	/**
	 * 전화번호을 설정합니다..
	 * 
	 * @param shippingPhone
	 *            전화번호
	 */
	public void setShippingPhone(String shippingPhone) {
		this.shippingPhone = shippingPhone;
	}

	/**
	 * 전화번호을 가져옵니다..
	 * 
	 * @return 전화번호
	 */
	public String getShippingPhone() {
		return this.shippingPhone;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((shippingSeq == null) ? 0 : shippingSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Shipping other = (Shipping) obj;
		if (shippingSeq == null) {
			if (other.shippingSeq != null) {
				return false;
			}
		} else if (!shippingSeq.equals(other.shippingSeq)) {
			return false;
		}
		return true;
	}

}
