package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 주문 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shoporder implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 주문번호. */
	private Integer shoporderSeq;

	/** 주문자명. */
	private String shoporderName;

	/** 주문자이메일. */
	private String shoporderEmail;

	/** 주문자휴대전화. */
	private String shoporderPhone;

	/** 결제수단. */
	private String shoporderPaymethod;

	/**
	 * 생성자.
	 */
	public Shoporder() {
	}
	

	public Shoporder(Integer shoporderSeq, String shoporderName, String shoporderEmail, String shoporderPhone,
			String shoporderPaymethod) {
		super();
		this.shoporderSeq = shoporderSeq;
		this.shoporderName = shoporderName;
		this.shoporderEmail = shoporderEmail;
		this.shoporderPhone = shoporderPhone;
		this.shoporderPaymethod = shoporderPaymethod;
	}


	/**
	 * 주문번호을 설정합니다..
	 * 
	 * @param shoporderSeq
	 *            주문번호
	 */
	public void setShoporderSeq(Integer shoporderSeq) {
		this.shoporderSeq = shoporderSeq;
	}

	/**
	 * 주문번호을 가져옵니다..
	 * 
	 * @return 주문번호
	 */
	public Integer getShoporderSeq() {
		return this.shoporderSeq;
	}

	/**
	 * 주문자명을 설정합니다..
	 * 
	 * @param shoporderName
	 *            주문자명
	 */
	public void setShoporderName(String shoporderName) {
		this.shoporderName = shoporderName;
	}

	/**
	 * 주문자명을 가져옵니다..
	 * 
	 * @return 주문자명
	 */
	public String getShoporderName() {
		return this.shoporderName;
	}

	/**
	 * 주문자이메일을 설정합니다..
	 * 
	 * @param shoporderEmail
	 *            주문자이메일
	 */
	public void setShoporderEmail(String shoporderEmail) {
		this.shoporderEmail = shoporderEmail;
	}

	/**
	 * 주문자이메일을 가져옵니다..
	 * 
	 * @return 주문자이메일
	 */
	public String getShoporderEmail() {
		return this.shoporderEmail;
	}

	/**
	 * 주문자휴대전화을 설정합니다..
	 * 
	 * @param shoporderPhone
	 *            주문자휴대전화
	 */
	public void setShoporderPhone(String shoporderPhone) {
		this.shoporderPhone = shoporderPhone;
	}

	/**
	 * 주문자휴대전화을 가져옵니다..
	 * 
	 * @return 주문자휴대전화
	 */
	public String getShoporderPhone() {
		return this.shoporderPhone;
	}

	/**
	 * 결제수단을 설정합니다..
	 * 
	 * @param shoporderPaymethod
	 *            결제수단
	 */
	public void setShoporderPaymethod(String shoporderPaymethod) {
		this.shoporderPaymethod = shoporderPaymethod;
	}

	/**
	 * 결제수단을 가져옵니다..
	 * 
	 * @return 결제수단
	 */
	public String getShoporderPaymethod() {
		return this.shoporderPaymethod;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((shoporderSeq == null) ? 0 : shoporderSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Shoporder other = (Shoporder) obj;
		if (shoporderSeq == null) {
			if (other.shoporderSeq != null) {
				return false;
			}
		} else if (!shoporderSeq.equals(other.shoporderSeq)) {
			return false;
		}
		return true;
	}

}
