package kosta1200.todayroom.dto;

import java.io.Serializable;

/**
 * 인테리어소품판매업체(신청서) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Vendor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 판매자정보번호. */
	private Integer vendorSeq;

	/** 회사이름. */
	private String vendorName;

	/** 사업자등록번호. */
	private String vendorLicense;

	/** 취급카테고리. */
	private String vendorCategory;

	/** 상품소개. */
	private String vendorIntroduction;

	/**
	 * 생성자.
	 */
	public Vendor() {
	}
	

	public Vendor(Integer vendorSeq, String vendorName, String vendorLicense, String vendorCategory,
			String vendorIntroduction) {
		super();
		this.vendorSeq = vendorSeq;
		this.vendorName = vendorName;
		this.vendorLicense = vendorLicense;
		this.vendorCategory = vendorCategory;
		this.vendorIntroduction = vendorIntroduction;
	}


	/**
	 * 판매자정보번호을 설정합니다..
	 * 
	 * @param vendorSeq
	 *            판매자정보번호
	 */
	public void setVendorSeq(Integer vendorSeq) {
		this.vendorSeq = vendorSeq;
	}

	/**
	 * 판매자정보번호을 가져옵니다..
	 * 
	 * @return 판매자정보번호
	 */
	public Integer getVendorSeq() {
		return this.vendorSeq;
	}

	/**
	 * 회사이름을 설정합니다..
	 * 
	 * @param vendorName
	 *            회사이름
	 */
	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	/**
	 * 회사이름을 가져옵니다..
	 * 
	 * @return 회사이름
	 */
	public String getVendorName() {
		return this.vendorName;
	}

	/**
	 * 사업자등록번호을 설정합니다..
	 * 
	 * @param vendorLicense
	 *            사업자등록번호
	 */
	public void setVendorLicense(String vendorLicense) {
		this.vendorLicense = vendorLicense;
	}

	/**
	 * 사업자등록번호을 가져옵니다..
	 * 
	 * @return 사업자등록번호
	 */
	public String getVendorLicense() {
		return this.vendorLicense;
	}

	/**
	 * 취급카테고리을 설정합니다..
	 * 
	 * @param vendorCategory
	 *            취급카테고리
	 */
	public void setVendorCategory(String vendorCategory) {
		this.vendorCategory = vendorCategory;
	}

	/**
	 * 취급카테고리을 가져옵니다..
	 * 
	 * @return 취급카테고리
	 */
	public String getVendorCategory() {
		return this.vendorCategory;
	}

	/**
	 * 상품소개을 설정합니다..
	 * 
	 * @param vendorIntroduction
	 *            상품소개
	 */
	public void setVendorIntroduction(String vendorIntroduction) {
		this.vendorIntroduction = vendorIntroduction;
	}

	/**
	 * 상품소개을 가져옵니다..
	 * 
	 * @return 상품소개
	 */
	public String getVendorIntroduction() {
		return this.vendorIntroduction;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((vendorSeq == null) ? 0 : vendorSeq.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Vendor other = (Vendor) obj;
		if (vendorSeq == null) {
			if (other.vendorSeq != null) {
				return false;
			}
		} else if (!vendorSeq.equals(other.vendorSeq)) {
			return false;
		}
		return true;
	}

}
